<?
$liens1=array(array(
              "Solution antivirus","",1,
              "Installation ","clamav/clamav-status.php","se3_is_admin",1,
              "Programmation","clamav/clamav-cron.php","se3_is_admin",2,
              "Journal","clamav/clamav-log.php","se3_is_admin",2,
              "Scan de fichier","clamav/clamav-scan.php","",1,
             ));
             $liens=array_merge($liens,$liens1);
?>
