#!/usr/bin/perl
# /usr/sbin/se3-clamav
# This file is part of the samba-edu project
#  it is distributed under the terms of the Gnu GPL license
# 
# Report any bug or comment to laurent Cooper <swirly@slis.fr>

# This programm connects to the se3db to read the directorys to scan
# It store the results of the clamav scan in the satabase;

use DBI;
use strict;
use File::Temp;

###
#
# Config file opening
#
###

my $dbhost=`cat /var/www/se3/includes/config.inc.php | grep \"dbhost=\" | cut -d = -f 2 |cut -d \\\" -f 2`;
chomp $dbhost;
my $dbname=`cat /var/www/se3/includes/config.inc.php | grep \"dbname=\" | cut -d = -f 2 |cut -d \\\" -f 2`;
chomp $dbname;
my $dbuser=`cat /var/www/se3/includes/config.inc.php | grep \"dbuser=\" | cut -d = -f 2 |cut -d \\\" -f 2`;
chomp $dbuser;
my $dbpass=`cat /var/www/se3/includes/config.inc.php | grep \"dbpass=\" | cut -d = -f 2 |cut -d \\\" -f 2`;
chomp $dbpass;


my $dsn="DBI:mysql:$dbname:$dbhost";
my $dbd = DBI->connect($dsn,$dbuser,$dbpass);

###
#
# Determines mail parameters
#
###

my $mailhandler= $dbd->prepare("SELECT value FROM params WHERE name=\'clamavmail\' ");
$mailhandler->execute;
my $mailhandler_row = $mailhandler->fetchrow_hashref;
my $has_to_mail = $mailhandler_row->{"value"};
my $admin_mail="";

if ($has_to_mail eq "1") {
  $mailhandler= $dbd->prepare("SELECT value FROM params WHERE name=\'clamavadm\' ");
  $mailhandler->execute;
  $mailhandler_row = $mailhandler->fetchrow_hashref;
  $admin_mail = $mailhandler_row->{"value"};
}

$mailhandler->finish;

###
#
# Determines which scan to make
#
###

my $frequency=shift;
my $sth= $dbd->prepare("SELECT * FROM clamav_dirs WHERE frequency=\'$frequency\' ");
$sth->execute;

my $ref_row;
while ($ref_row = $sth->fetchrow_hashref) {
  my $directory = $ref_row->{"directory"};
  my $remove = $ref_row->{"remove"};
  my $tmp_file=tmpnam();

#############################
#
# Now scan the directory appropriatly
#
#############################
  if ($remove eq "0") {
    `/usr/bin/nice -n 15 /usr/bin/clamscan -ri -l $tmp_file  $directory >> /dev/null 2>&1`;
  } else {             
    `/usr/bin/nice -n 15 /usr/bin/clamscan --remove -ri -l $tmp_file  $directory >> /dev/null 2>&1`;
  }

#############################
#
# Flush the result
#
#############################
  my $virus_found = 0;
  open(CLAMSCAN,$tmp_file);
  my $line;
  my $summary="";
  my $scan_result="";
  my $mode="scan";
  while (defined ($line=<CLAMSCAN>)) {
    if ($mode eq "scan") {
      if( $line =~ /--\ssummary\s--/) {
        $mode="summary";
      } else {
        $scan_result .= $line;}
    } else {
      if ($line =~ /^Infected files:/) {
        $virus_found = substr($line,16);
        chomp($virus_found);
        $virus_found =~ s/^\s+//;
        $virus_found =~ s/\s+$//;
      }	
      $summary .= $line;
    }
  }

#############################
#
# Put it in the database
#
#############################
  ## Added to  protect SQL syntax, thank to Jean Le Bail
  $summary =~ s/\'/\\\'/g;
  $scan_result =~ s/\'/\\\'/g;
  ##
  $dbd->do("INSERT INTO clamav_scan (directory,summary,result) VALUES ('".$directory."','".$summary."','".$scan_result."')");

#################################
#
# Mail warning for found viruses
#
#################################

  if ( ($has_to_mail eq "1") && ($virus_found ne "0") ) {

    open MAIL,"|mail -s \"[se3-clamav] virus sur le serveur se3 \" $admin_mail";
    print MAIL "Voici le resume de la recherche de virus \n ------------- \n";
    print MAIL $summary;
    print MAIL "\n ------------- \n et voici le resultat du scan \n";
    print MAIL $scan_result;
    close MAIL;
  }

#############################
#
# Destroy temporary file
#
#############################
  unlink($tmp_file);
}

$sth->finish();

$dbd->disconnect();